Convert test class to JUnit 4 and fix warnings
For a record:
The test testDataSendASYNC() is known to fail.
java.lang.AssertionError: Checking success messages. expected:<10000> but was:<1576>
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.apache.catalina.tribes.test.channel.TestDataIntegrity.testDataSendASYNCM(TestDataIntegrity.java:127)

What is needed to fix it is TBD. In Tomcat 7 build.xml these tests are excluded from testsuite runs with
<!-- Exclude the tests known to fail -->
<exclude name="org/apache/catalina/tribes/test/**" />

git-svn-id: https://svn.apache.org/repos/asf/tomcat/tc6.0.x/trunk@1714567 13f79535-47bb-0310-9956-ffa450edef68